#!/bin/sh

load() {
    curtime=`cat /proc/uptime | awk -F ' ' '{print $1}'`
    echo "[$curtime] start valetudo-daemon"
    start-stop-daemon -S -b -q -m -p /var/run/valetudo-daemon.pid -x /usr/local/bin/valetudo-daemon.sh
}

unload() {
    echo "Stopping logging" >/dev/kmsg
    start-stop-daemon -K -q -p /var/run/valetudo-daemon.pid
    killall -9 valetudo
}

case "$1" in
    start)
        load
        ;;
    stop)
        unload
        ;;
    restart)
        unload
        load
        ;;
    *)
        echo "$0 <start/stop/restart>"
        ;;
esac

